"""Add class_id to Topic and make Occurrence.resource_id optional

Revision ID: 1aa19b958f63
Revises: 62b8ef13461c
Create Date: 2026-02-27 23:42:22.189951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa19b958f63'
down_revision: Union[str, Sequence[str], None] = '62b8ef13461c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('occurrence', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('topic', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'class_id')
    op.alter_column('occurrence', 'resource_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
