"""Rename Grade to Score, add TopicScore

Revision ID: 2e08acaa0561
Revises: 44e79900a1bf
Create Date: 2026-02-26 19:22:55.805894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e08acaa0561'
down_revision: Union[str, Sequence[str], None] = '44e79900a1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grade',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('grade_assignment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('grade_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('grade_pkey'))
    )
    # ### end Alembic commands ###
