"""Remove class_id from topic

Revision ID: 479bd71c8df9
Revises: 1aa19b958f63
Create Date: 2026-02-27 23:58:05.181207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '479bd71c8df9'
down_revision: Union[str, Sequence[str], None] = '1aa19b958f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('topic_class_id_fkey'), 'topic', type_='foreignkey')
    op.drop_column('topic', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('topic_class_id_fkey'), 'topic', 'class', ['class_id'], ['id'])
    # ### end Alembic commands ###
