"""refactor schemas

Revision ID: 67707b3b9deb
Revises: 2e08acaa0561
Create Date: 2026-02-27 14:19:48.305126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67707b3b9deb'
down_revision: Union[str, Sequence[str], None] = '2e08acaa0561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignmentgrade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=False),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionresponse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('graded', sa.Boolean(), nullable=False),
    sa.Column('grader', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marks', sa.Float(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('score')
    op.drop_column('assignment', 'questions')
    op.add_column('topicscore', sa.Column('response_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('topicscore_assignment_id_fkey'), 'topicscore', type_='foreignkey')
    op.drop_constraint(op.f('topicscore_student_id_fkey'), 'topicscore', type_='foreignkey')
    op.create_foreign_key(None, 'topicscore', 'questionresponse', ['response_id'], ['id'])
    op.drop_column('topicscore', 'assignment_id')
    op.drop_column('topicscore', 'student_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topicscore', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('topicscore', sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'topicscore', type_='foreignkey')
    op.create_foreign_key(op.f('topicscore_student_id_fkey'), 'topicscore', 'user', ['student_id'], ['id'])
    op.create_foreign_key(op.f('topicscore_assignment_id_fkey'), 'topicscore', 'assignment', ['assignment_id'], ['id'])
    op.drop_column('topicscore', 'response_id')
    op.add_column('assignment', sa.Column('questions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.create_table('score',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('marks', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('score_assignment_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], name=op.f('score_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('score_pkey'))
    )
    op.drop_table('questionresponse')
    op.drop_table('question')
    op.drop_table('assignmentgrade')
    # ### end Alembic commands ###
