"""add feedback to questionresponse

Revision ID: dc5f91d570e9
Revises: 67707b3b9deb
Create Date: 2026-02-27 17:56:59.440516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dc5f91d570e9'
down_revision: Union[str, Sequence[str], None] = '67707b3b9deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionresponse', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questionresponse', 'feedback')
    # ### end Alembic commands ###
